steps:
- id: "Build and Push Container Image: Backend"
  name: "gcr.io/cloud-builders/docker:latest"
  entrypoint: "/bin/bash"
  args:
    - "-c"
    - |
      docker build -t europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/hello-world-shell:latest .
      docker push europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/hello-world-shell:latest
images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/hello-world-shell:latest'
options:
  requestedVerifyOption: VERIFIED
